version: '3.8'

services:
  faiss-api:
    image: faiss-api:latest
    # Or use pre-built image from registry:
    # image: your-registry/faiss-api:latest
    
    ports:
      - "8000:8000"
    
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_TOKEN=${API_TOKEN}
      - STORAGE_DIR=/app/storage
    
    volumes:
      # Single volume for all persistent data (messages + indexes)
      - ./storage:/app/storage
    
    restart: unless-stopped
    
    # Optional: resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M