# fly.toml app configuration file generated for faiss-api
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "faiss-api"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  PORT = "8000"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "faiss_data"
  destination = "/app/data"

[[statics]]
  guest_path = "/app/index"
  url_prefix = "/static/"